version: "3"

volumes:
  mysql-volume:
  golang-volume:
  auth-volume:
  rights-volume:
  user-manage-volume:

services:
  golang:
    build: app
    ports:
      - 80:80
    volumes:
      - ./app:/workspace
      - golang-volume:/go
    working_dir: /workspace
    env_file:
      - ./.env
  auth:
    build: auth/app
    volumes:
      - ./auth/app:/workspace
      - auth-volume:/go
    working_dir: /workspace
    env_file:
      - ./auth/.env
  rights:
    build: rights/app
    volumes:
      - ./rights/app:/workspace
      - rights-volume:/go
    working_dir: /workspace
    env_file:
      - ./rights/.env
  user-manage:
    build: user-manage/app
    volumes:
      - ./user-manage/app:/workspace
      - user-manage-volume:/go
    working_dir: /workspace
    env_file:
      - ./user-manage/.env
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    env_file:
      - ./.env
