name: Continuous Integration

on: [push, pull_request]

jobs:
  unit-tests:

    env:
      TZ: Asia/Tokyo

    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Unit Test
        working-directory: ./app
        run: go test -race -coverprofile="coverage.txt" -covermode=atomic ./...

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./app
